version: 2

submodules:
  include: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - python3-dev
    - graphviz
    - cmake

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
    - requirements: requirements.txt
